version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec foreman start"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true