FROM ruby:2.5
ENV LANG C.UTF-8
ENV APP /app
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir $APP
WORKDIR $APP
COPY Gemfile $APP/Gemfile
COPY Gemfile.lock $APP/Gemfile.lock
RUN bundle install
COPY package.json $APP/package.json
COPY yarn.lock $APP/yarn.lock
RUN yarn install
COPY . $APP