default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= Rails.application.secrets.config[:database][:mysql][:database] %>
  username: <%= Rails.application.secrets.config[:database][:mysql][:username] %>
  password: <%= Rails.application.secrets.config[:database][:mysql][:password] %>
  host:     <%= Rails.application.secrets.config[:database][:mysql][:host] %>
  socket:   <%= Rails.application.secrets.config[:database][:mysql][:socket] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: otayori_box_test

production:
  <<: *default